name: dicoding_restaurant_app
description: A new Flutter project.
# api zomato.com
# https://developers.zomato.com/api?lang=id
# e0d4a9e5f5e6266f9438a38745a81c77

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.2.5
  flutter_staggered_grid_view: ^0.3.3
  google_fonts: ^1.1.0
  intl: ^0.16.1
  android_alarm_manager: ^0.4.5+11
  flutter_local_notifications: ^1.4.4+4
  rxdart: ^0.23.1
  provider: ^4.3.3
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/restaurant.json
    - assets/fonts/ComicNeue-Regular.ttf
    - assets/fonts/TenorSans-Regular.ttf
    - assets/meal.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
